### ISSUE TITLE
Help me i can't get it to work

### ISSUE THREAD

**Issue by danko79** [msolajic/c264-magic-cart#1]
Hi,i need help with this cartridge programmed the GAL20V8B-15LP set the jumpers for AM26F040B and make a 512KB file with prg games with zzarko-magic-cartridge-generator-fa8be5cd43f2 but when insert the cartridge it does not work, tested your other cartridges with success.

https://i.postimg.cc/tTB5dr2J/c264-front.jpg
https://i.postimg.cc/Y9rRWcNT/c264-back.jpg

**Comment by msolajic** [comment]
Can you test the binary compilation file with VICE 3.6? This will rule out software issues, at least.

**Comment by danko79** [comment]
Hi,yes test the .BIN file with GTK3VICE-3.6.0-win64 same
problem,attach the file .bin and .prg pack. 
Please let me know! 

Il
24.01.2022 14:03 Marko Šolajić ha scritto: 

> Can you test the binary
compilation file with VICE 3.6? This will rule out software issues, at
least. 
> 
> --
> Reply to this email directly, view it on GitHub [1],
or unsubscribe [2].
> You are receiving this because you authored the
thread.Message ID: @github.com>
  


Con Tiscali Mobile Smart 70 hai 70 GB in 4G, minuti illimitati e 100 SMS a soli 7,99€ al mese http://tisca.li/Smart70

**Comment by zzarko** [comment]
Can you send your whole directory with generator script, cartridge
configuration, prg files and generated BIN file? Then I can check what the
problem is.
Also, send the exact command line you used to generate BIN file.

Cheers,
Žarko

*Sent from my Commodore 64*

**Comment by danko79** [comment]
ok the script is "python crtgen.py -c" in attach my directory,can you
create a file for me so i see if it works?

Il 24.01.2022 15:06 zzarko
ha scritto: 

> Can you send your whole directory with generator script,
cartridge
> configuration, prg files and generated BIN file? Then I can
check what the
> problem is.
> Also, send the exact command line you
used to generate BIN file.
> 
> Cheers,
> Žarko
> 
> *Sent from my
Commodore 64*
> 
> On Mon, Jan 24, 2022 at 2:12 PM danko79 ***@***.***>
wrote:
> 
> >
> > Hi,yes test the .BIN file with GTK3VICE-3.6.0-win64
same
> > problem,attach the file .bin and .prg pack.
> > Please let me
know!
> >
> > Il
> > 24.01.2022 14:03 Marko Šolajić ha scritto:
> >
> >
> Can you test the binary
> > compilation file with VICE 3.6? This will
rule out software issues, at
> > least.
> > >
> > > --
> > > Reply to
this email directly, view it on GitHub [1],
> > or unsubscribe [2].
> >
> You are receiving this because you authored the
> > thread.Message ID:
@github.com>
> >
> >
> >
> > Con Tiscali Mobile Smart 70 hai 70 GB in
4G, minuti illimitati e 100 SMS a
> > soli 7,99EUR al mese
http://tisca.li/Smart70
> >
> > --
> > Reply to this email directly,
view it on GitHub
> > ,
> > or unsubscribe
> > 
> > .
> > Triage
notifications on the go with GitHub Mobile for iOS
> > 
> > or Android
>
> .
> >
> > You are receiving this because you are subscribed to this
thread.Message
> > ID: ***@***.***>
> >
> 
> --
> Reply to this email
directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving
this because you authored the thread.Message ID: @github.com>
 



Con Tiscali Mobile Smart 70 hai 70 GB in 4G, minuti illimitati e 100 SMS a soli 7,99€ al mese http://tisca.li/Smart70

**Comment by msolajic** [comment]
Attachments don't get trough if you are using GitHub, please upload to a file sharing service and post the link here.

**Comment by danko79** [comment]
Hi, the link http://www.easybytez.com/q8i78399koon
I used the wrong parameter that's why it didn't work! "python crtgen.py -c is for C64" the correct is "python crtgen.py -p for Plus4"
now the cartridge works but most games don't work is there any other problem?

**Comment by zzarko** [comment]
Yes, that was exactly why I wanted to see the exact command line. "-p" is
the correct option.

Regarding the games that do not work, I found these:
Auto Zone.prg
Exploding Fist.prg
Invaders Live Wire.prg
Joey.prg
Kane.prg
Kingsoft Tennis.prg
Leapinlouie.prg
Monkey Kong.prg
Monster Hunter.prg
Oneman And His Droid.prg
Pac Mac.prg
Return Of Rockman.prg

Some of them have non-standard loading address (standard is $1001 or
$4001), for those you need to supply start address:
Invaders Live Wire.prg
Kingsoft Tennis.prg
Monkey Kong.prg

As for the rest, they do not work in xplus4 emulator (3.6.1) at all (at
least on my computer, when started directly as PRG files), so there is no
way that they could work from cartridge in xplus4:
Auto Zone.prg
Exploding Fist.prg
Joey.prg
Kane.prg
Kingsoft Tennis.prg
Leapinlouie.prg
Monster Hunter.prg
Oneman And His Droid.prg
Pac Mac.prg
Return Of Rockman.prg
They might work on a real Plus/4, but you'll need to check that.

Cheers,
Žarko

*Sent from my Commodore 64*

**Comment by danko79** [comment]
Many thanks for your support! as soon have some time test all games, thanks for your patience!

**Comment by danko79** [comment]
Hi,I found that some games that play but only if it is the first on
the list, I tried to replicate the same game 5/6 times to create a 64KB
file the cartridge works but of the same game only the first one doesn't
seem strange to you? 
can you try too?

**Comment by zzarko** [comment]
Send me an archive with everything (like before), tell me how exactly to
reproduce the problem, and I can take a look.

Cheers,
Žarko

*Sent from my Commodore 64*

**Comment by danko79** [comment]
Hi, I've done a lot of tests! and understood that the games work as long as it is the first on list otherwise it doesn't work anymore, i make a 3 different BIN files 128KB has a different primary game as you can verify it works too all the games below do not works only if you make it happen first, i used a W27C010-15 flash for test all.
the command used is python crtgen.py -p

http://www.easybytez.com/rdnzr148nvzw

Please let me know,I can't understand why it does this.

**Comment by msolajic** [comment]
Hi, i did some tests with your 128k images, and all of them work well. I tested with 29EE010 flash which is the same pinout as W27C010. To me, this looks like a banking issue, because the menu and the first game (either one of those in the archive) are less than 16 kilobytes in total. So, please check the GAL or 74LS273, as they are the most likely problem.

**Comment by msolajic** [comment]
Also, is the GAL programmed and verified? Because I'm getting the same behaviour as yours without the GAL inserted on the board. Without it, only the first game works.

**Comment by danko79** [comment]
The GAL programmed several times, if my images works i can try to replace the 74LS273,then will let you know.

**Comment by danko79** [comment]
Hi,i try to replace 74LS273 same problem,when replace GAL with another one programmed cartridge works fine!
Many thanks!!!!!

**Comment by msolajic** [comment]
You're welcome.

**Comment by danko79** [comment]
Hi,sorry if re-open this, but it is the only way to contact you, I wanted to know if these are compatible the GAL20V8QS-15LNC. Regards
